---
- name: Install agent on linux servers
  hosts: linux
  tasks:
    - name: Download agent
      get_url: 
        url: https://aws-application-migration-service-{{ region }}.s3.{{ region }}.amazonaws.com/latest/linux/aws-replication-installer-init.py 
        dest: /tmp/aws-replication-installer-init.py

    - name: Ansible apt install python3
      become: true
      become_method: sudo
      apt:
        name: python3
        state: present

    - name: run agent
      become: true
      shell: echo |python3 /tmp/aws-replication-installer-init.py --region {{ region }} --aws-access-key-id {{ lookup('env', 'AWS_ACCESS_KEY_ID') }} --aws-secret-access-key {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} 
          
    # - name: check var
    #   debug:
    #     msg: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"

- name: Install agent on windows servers
  hosts: win_ssh,win_winrm
  tasks:
    - name: Download agent
      ansible.windows.win_get_url:
        url: "https://aws-application-migration-service-{{ region }}.s3.{{ region }}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe"
        dest: C:\AwsReplicationWindowsInstaller.exe

   
    - name: run agent
      win_shell: $nl = [Environment]::NewLine ; $nl |C:\AwsReplicationWindowsInstaller.exe --region {{ region }} --aws-access-key-id {{ lookup('env', 'AWS_ACCESS_KEY_ID') }} --aws-secret-access-key {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}
